// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	movie "datacenter/movies/api/internal/handler/movie"
	"datacenter/movies/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/movies/ping",
				Handler: movie.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/movies/search",
				Handler: movie.SearchHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Usercheck},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/movies/info",
					Handler: movie.MovieInfoHandler(serverCtx),
				},
			}...,
		),
	)
}
