version: "3"

services:
  adminer:
    image: adminer
    container_name: datacenter-adminer
    ports: 
      - 9434:8080
    links:
      - db
    environment: 
      - MYSQL_PASSWORD=admin
  db:
    image: mysql:8.0.21
    container_name: mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=admin
    volumes: 
      - /home/dev/mysql8:/var/lib/mysql
    restart: always
  cache:
    image: sameersbn/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment: 
      - REDIS_PASSWORD=admin
    volumes:
      - /home/dev/redis:/var/lib/redis
  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd
    ports: 
      - 2379:2379
      - 2380:2380
    volumes: 
      - /home/dev/etcd:/etcd-data
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - --listen-client-urls
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"
  es:
    image: spencezhou/elasticsearch:7.6.2
    container_name: es
    environment: 
      - discovery.type=single-node
    ports: 
      - 9200:9200
      - 9300:9300
    volumes: 
      - /home/dev/elasticsearch:/usr/share/elasticsearch/data