// Code generated by goctl. DO NOT EDIT.
package types

type MovieReq struct {
	Id string `json:"id"` //基本一个手机号码就完事
}

type MovieReply struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Url         string `json:"url"`
}
