// Code generated by goctl. DO NOT EDIT!
// Source: movie.proto

package server

import (
	"context"

	"datacenter/movies/rpc/internal/logic"
	"datacenter/movies/rpc/internal/svc"
	"datacenter/movies/rpc/movie"
)

type MovieServer struct {
	svcCtx *svc.ServiceContext
}

func NewMovieServer(svcCtx *svc.ServiceContext) *MovieServer {
	return &MovieServer{
		svcCtx: svcCtx,
	}
}

func (s *MovieServer) Search(ctx context.Context, in *movie.MovieRequest) (*movie.MovieResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

func (s *MovieServer) Create(ctx context.Context, in *movie.MovieRequest) (*movie.MovieResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *MovieServer) Delete(ctx context.Context, in *movie.MovieRequest) (*movie.MovieResponse, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *MovieServer) Update(ctx context.Context, in *movie.MovieRequest) (*movie.MovieResponse, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}
